name: Publish Docker image
on:
  # push:
  #   branches: master
  release:
    types:
      - published
  # push:
  #   tags:
  #     - "v*.*.*"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push release tag
        id: docker_build_tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maiara/gt-actions:${{ github.event.release.tag_name }}
      - name: Build and push latest release
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maiara/gt-actions:latest